module.exports.categoryController = require('./category.controller')
module.exports.userauthController = require('./userauth.controller')
module.exports.productsController = require('./products.controller')
module.exports.cartController = require('./cart.controller')
module.exports.wishlistController = require('./wishlist.controller')